// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-_lrI63GLrU7raQGIKIUsRm_y95JcZ5A',
    appId: '1:41962028052:web:880a0ff84873735c133b01',
    messagingSenderId: '41962028052',
    projectId: 'fluttertest0825',
    authDomain: 'fluttertest0825.firebaseapp.com',
    storageBucket: 'fluttertest0825.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg1qLnoDvZvDyYoFJSEgD284utyqu7d6U',
    appId: '1:41962028052:android:440149bcf8a53e37133b01',
    messagingSenderId: '41962028052',
    projectId: 'fluttertest0825',
    storageBucket: 'fluttertest0825.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo_MrKdppT5uX4xqQdRlSBawKNDn3OzY4',
    appId: '1:41962028052:ios:fc58196a6abc3516133b01',
    messagingSenderId: '41962028052',
    projectId: 'fluttertest0825',
    storageBucket: 'fluttertest0825.appspot.com',
    iosClientId: '41962028052-3gkr9e8tjufm1jl7mhnmopplr9sq0rg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo_MrKdppT5uX4xqQdRlSBawKNDn3OzY4',
    appId: '1:41962028052:ios:0a5198b3512e599d133b01',
    messagingSenderId: '41962028052',
    projectId: 'fluttertest0825',
    storageBucket: 'fluttertest0825.appspot.com',
    iosClientId: '41962028052-1qi8ktiaq0babbo68bh630o2fvddlg9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest.RunnerTests',
  );
}
